### PR TITLE
Fix/network mutex

### LINKED ISSUE #74: "This NetworkName is processing" error
# Provider version
terraform-provider-nifcloud v1.3.0

# Terraform Configuration File
<pre>
resource "nifcloud_private_lan" "privatelan01" {
      private_lan_name  = "pvlan01"
      availability_zone = "east-11"
      cidr_block        = "192.168.10.0/24"
      accounting_type   = "2"
}

resource "nifcloud_router" "router01" {
      name              = "router01"
      availability_zone = "east-11"
      type              = "small"
      accounting_type   = "2"
      network_interface {
          network_name  = nifcloud_private_lan.privatelan01.private_lan_name
          ip_address    = "192.168.10.250"
          dhcp          = false
      }
      network_interface {
          network_id      = "net-COMMON_GLOBAL"
      }
      security_group = nifcloud_security_group.fwgroup02.group_name
}

resource "nifcloud_vpn_gateway" "vpngw01" {
      name              = "vpngw01"
      availability_zone = "east-11"
      type              = "small"
      accounting_type   = "2"
      network_name      = nifcloud_private_lan.privatelan01.private_lan_name
      ip_address        = "192.168.10.251"
      security_group    = nifcloud_security_group.fwgroup03.group_name
}

resource "nifcloud_vpn_connection" "vpnconnection01" {
      vpn_gateway_name                                     = nifcloud_vpn_gateway.vpngw01.name
      customer_gateway_name                                = nifcloud_customer_gateway.customergw01.name
      type                                                 = "IPsec VTI"
      ipsec_config_internet_key_exchange                   = "IKEv2"
      ipsec_config_encryption_algorithm                    = "AES256"
      ipsec_config_hash_algorithm                          = "SHA256"
}

resource "nifcloud_elb" "elb01" {
      elb_name                                    = "elb01"
      availability_zone                           = "east-11"
      network_volume                              = "10"
      accounting_type                             = "2"
      balancing_type                              = "1"
      protocol                                    = "HTTPS"
      instance_port                               = "443"
      lb_port                                     = "80"
      health_check_target                         = "ICMP"

      health_check_interval                       = "30"
      unhealthy_threshold                         = "2"
      network_interface {
          network_name   = nifcloud_private_lan.privatelan01.private_lan_name
          ip_address     = "192.168.10.100"
      }
      instances                                   = [
          nifcloud_instance.server01.instance_id,
      ]
}

resource "nifcloud_customer_gateway" "customergw01" {
      name                = "cgw01"
      ip_address          = "175.180.20.2"
      type                = "IPsec VTI"
      lan_side_cidr_block = "192.168.20.0/24"
}

resource "nifcloud_web_proxy" "webproxy01" {
      router_id                     = nifcloud_router.router01.id
      listen_interface_network_name = nifcloud_private_lan.privatelan01.private_lan_name
      listen_port                   = "8080"
      bypass_interface_network_id   = "net-COMMON_GLOBAL"
      name_server                   = "8.8.8.8"
}

resource "nifcloud_security_group" "fwgroup01" {
      group_name        = "fw01"
      availability_zone = "east-11"
      log_limit         = "1000"
}
resource "nifcloud_security_group" "fwgroup02" {
      group_name        = "fw02"
      availability_zone = "east-11"
      log_limit         = "1000"
}
resource "nifcloud_security_group" "fwgroup03" {
      group_name        = "fw03"
      availability_zone = "east-11"
      log_limit         = "1000"
}

resource "nifcloud_security_group_rule" "fw_inrule01" {
      security_group_names       = [nifcloud_security_group.fwgroup01.group_name]
      protocol                   = "TCP"
      from_port                  = "22"
      to_port                    = "22"
      cidr_ip                    = "192.168.10.0/24"
      type                       = "IN"
}
resource "nifcloud_security_group_rule" "fw_inrule02" {
      security_group_names       = [nifcloud_security_group.fwgroup01.group_name]
      protocol                   = "TCP"
      from_port                  = "3389"
      to_port                    = "3389"
      cidr_ip                    = "192.168.10.0/24"
      type                       = "IN"
}
resource "nifcloud_security_group_rule" "fw_inrule03" {
      security_group_names       = [nifcloud_security_group.fwgroup01.group_name]
      protocol                   = "TCP"
      from_port                  = "5985"
      to_port                    = "5986"
      cidr_ip                    = "192.168.10.0/24"
      type                       = "IN"
}
resource "nifcloud_security_group_rule" "fw_inrule04" {
      security_group_names       = [nifcloud_security_group.fwgroup02.group_name]
      protocol                   = "TCP"
      from_port                  = "8080"
      to_port                    = "8080"
      cidr_ip                    = "192.168.10.0/24"
      type                       = "IN"
}
</pre>

# Steps to Reproduce
Use the above configuration and execute apply. Then, error occures.
The error message is as follows:

<pre>
Error: failed creating router:
Server.ResourceIncorrectState.Network.Processing: The NetworkName
'pvlanprd01' cannot create. This NetworkName is processing.
</pre>

* Supplements
I contacted NIFCLOUD support and received answer that this is  provider problem. (NCSP-00078566)

Could you correct it as soon as possible?

### LINKED ISSUE #85: There was a network creation error
Could you tell me what could be the cause of the error?
For information, currently, the error is not reproduced.

# Provider version
terraform-provider-nifcloud v1.3.2

# Terraform Configuration File
<pre>
resource "nifcloud_private_lan" "privatelan01" {
    private_lan_name  = "plan1"
    availability_zone = "east-12"
    cidr_block        = "192.168.1.0/24"
    accounting_type   = "2"
}
resource "nifcloud_private_lan" "privatelan02" {
    private_lan_name  = "plan2"
    availability_zone = "east-12"
    cidr_block        = "192.168.2.0/24"
    accounting_type   = "2"
}
resource "nifcloud_private_lan" "privatelan03" {
    private_lan_name  = "plan3"
    availability_zone = "east-12"
    cidr_block        = "192.168.3.0/24"
    accounting_type   = "2"
}

resource "nifcloud_router" "router01" {
    name              = "router1"
    availability_zone = "east-12"
    type              = "small"
    accounting_type   = "2"
    network_interface {
        network_name    = nifcloud_private_lan.privatelan02.private_lan_name
    }
    network_interface {
        network_name    = nifcloud_private_lan.privatelan03.private_lan_name
    }
}

resource "nifcloud_vpn_gateway" "vpngw01" {
    name              = "vpngw1"
    availability_zone = "east-12"
    type              = "small"
    accounting_type   = "2"
    network_name      = nifcloud_private_lan.privatelan01.private_lan_name
    description       = "vpngw 1"
}
</pre>

# Steps to Reproduce
Use the above configuration and execute apply. Then, error occures.
The error message is as follows:

<pre>
    Error: failed creating private_lan: Server.ProcessingFailure.Network.Create: Failed to create a network.
            status code: 500, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  
      on fjcloud-v.tf line 22, in resource "nifcloud_private_lan" "privatelan02":
      22: resource "nifcloud_private_lan" "privatelan02" {
</pre>

# Supplement
On July 2, 2021 (JST), the error was reproduced several times, but on July 5 (JST), the error no longer occurred.

### PR DESCRIPTION
**Pull request by fuku2014**
## Description

* Fix #74 
* Fix #85

## How Has This Been Tested?

- [ ] Resoved #74 
- [ ] Resolved #85
- [ ] Run the acceptance test.
```
TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_Router
```
```
TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_ELB
```
```
TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_NetworkInterface
```
```
TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_VpnGateway
```

## Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

### CODE REVIEW

**Comment by tily** [comment]
@fuku2014 3rd & 4th tests failed!

```
$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_Router
=== RUN   TestAcc_Router
=== PAUSE TestAcc_Router
=== CONT  TestAcc_Router
--- PASS: TestAcc_Router (619.90s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    619.928s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]

$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_ELB
=== RUN   TestAcc_ELBListener
=== PAUSE TestAcc_ELBListener
=== RUN   TestAcc_ELB
=== PAUSE TestAcc_ELB
=== CONT  TestAcc_ELBListener
=== CONT  TestAcc_ELB
--- PASS: TestAcc_ELBListener (587.35s)
--- PASS: TestAcc_ELB (837.94s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    838.812s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]

$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_NetworkInterface
=== RUN   TestAcc_NetworkInterface
=== PAUSE TestAcc_NetworkInterface
=== CONT  TestAcc_NetworkInterface
    network_interface_test.go:37: Step 1/3 error: Check failed: Check 5/8 error: nifcloud_network_interface.basic: Attribute 'description' expected "tfacc3smjzk9", got ""
--- FAIL: TestAcc_NetworkInterface (280.18s)
FAIL
FAIL    github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    280.212s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
FAIL

$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_VpnGateway
=== RUN   TestAcc_VpnGateway
=== PAUSE TestAcc_VpnGateway
=== CONT  TestAcc_VpnGateway
    vpn_gateway_test.go:37: Step 2/3 error: Error running apply: exit status 1
        
        Error: failed waiting for vpngateway available: ResourceNotReady: exceeded wait attempts
        
          with nifcloud_vpn_gateway.basic,
          on terraform_plugin_test.tf line 5, in resource "nifcloud_vpn_gateway" "basic":
           5: resource "nifcloud_vpn_gateway" "basic" {
        
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: failed deleting: Client.Inoperable.RouteTable.InUse: The routeTable 'rtb-05qch2gz' has dependencies and cannot be delete.
                status code: 500, request id: 0b638343-bfa5-4aab-a51a-d056dbcf3fc4
        
        
        Error: failed deleting vpngateway: Server.ResourceIncorrectState.VpnGateway.Processing: The VpnGatewayId 'vgw-0k87j2az' cannot delete. This VpnGatewayId is processing.
                status code: 500, request id: 5ff4b487-c70f-4470-b036-3e5c341ff444
        
--- FAIL: TestAcc_VpnGateway (1096.22s)
FAIL
FAIL    github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    1096.273s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
FAIL
```

**Comment by fuku2014** [comment]
Hi @tily 

It`s fixed! try it again 🐭

**Comment by tily** [comment]
@fuku2014 Thank you! All the tests passed. :tada:
```
$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_Router
=== RUN   TestAcc_Router
=== PAUSE TestAcc_Router
=== CONT  TestAcc_Router
--- PASS: TestAcc_Router (654.26s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    654.314s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_ELB
=== RUN   TestAcc_ELBListener
=== PAUSE TestAcc_ELBListener
=== RUN   TestAcc_ELB
=== PAUSE TestAcc_ELB
=== CONT  TestAcc_ELBListener
=== CONT  TestAcc_ELB
--- PASS: TestAcc_ELBListener (644.58s)
--- PASS: TestAcc_ELB (846.22s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    846.527s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_NetworkInterface
=== RUN   TestAcc_NetworkInterface
=== PAUSE TestAcc_NetworkInterface
=== CONT  TestAcc_NetworkInterface
--- PASS: TestAcc_NetworkInterface (400.42s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    400.466s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
$ TF_ACC=1 go test ./nifcloud/acc/... -v -count 1 -parallel 20 -timeout 360m -run TestAcc_VpnGateway
=== RUN   TestAcc_VpnGateway
=== PAUSE TestAcc_VpnGateway
=== CONT  TestAcc_VpnGateway
--- PASS: TestAcc_VpnGateway (486.41s)
PASS
ok      github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc    486.430s
?       github.com/nifcloud/terraform-provider-nifcloud/nifcloud/acc/helper     [no test files]
```

**Review by tily — APPROVED** [review]
LGTM!
![https://media.giphy.com/media/AQMPz2P5kksiMyUobY/giphy.gif?cid=ecf05e47pi9oy6auhcbkk0nvonf887pnxvm3ibv12htxszt4&rid=giphy.gif&ct=g]

**Pull request merged**
